import { ChangeDetectorRef, Component } from '@angular/core';
import { Job } from './Job';

@Component({
  selector: 'app-job',
  templateUrl: './job.component.html',
  styleUrls: ['./job.component.scss']
})
export class JobComponent {
  jobs!: Job[];

  constructor(private changeDetectorRef: ChangeDetectorRef) {

    this.jobs = [
      {
        "employer_name": "EY",
        "employer_logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/EY_logo_2019.svg/220px-EY_logo_2019.svg.png",
        "employer_website": "http://www.ey.com",
        "employer_company_type": "Accounting",
        "job_publisher": "Jobrapido.com",
        "job_id": "5F_0VRsAOOcAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "(QT-128) - Project Manager",
        "job_apply_link": "https://in.jobrapido.com/jobpreview/235656904",
        "job_description": "Your key responsibilities Support the development of the project business case with the customer team Lead the development of the project charter and scope, and ensure delivery of the solution to schedule, budget and scope Plan the project based on a defined need, resulting in a detailed scope/budget/schedule baseline Develop objectives, phasing and content of the project to deliver on the business case benefits, budget and timescales Monitor and control the work to ensure that the project remains on track and in control Plan for and manage change Report on variances to the approved project baseline Deliver projects aligned to overall business and technology strategies and architectures Interface and communicate with project team, management, stakeholders, and vendors Manage to the objectives and plan by thorough risk, issue and change management across both business and IT parts of the project Ensure that quality project standards are met as prescribed by IT Services and within defined governance processes Close the project to formalize acceptance of the project result and release project resources Skills and attributes for success Program Management (ET): Develop and manage plans to address program strengths, weaknesses, opportunities and threats // Analytical skills and problem-solving skills needed to manage multiple factors on a program simultaneously Project Risk Management (ET): Anticipates problems before they occur; defines the problem or risk; identifies possible causes; works with team to identify solutions; selects and implements most appropriate solution // Proactively identify risks and issues on programs - leading team to develop risk management and issues management plans // Identifies potential points of contention for missed deliverables; creates and implements strategy to mitigate shortfalls in timeline and budget Relationship Building: Develops strong relationships with diverse stakeholders by anticipating needs, collaborating across teams, fostering commitment and asking for feedback. Cultivates internal and external networks and leverages them to connect stakeholders with subject-matter specialists. Finds the right cadence with stakeholders to become a trusted business advisor. Applies diplomacy, interpersonal skills and conflict resolution. Shows versatility in understanding and working in culturally diverse environments Resource Management: The capability to effectively monitor and balance resource workloads across the portfolio, program(s) and projects taking into account changes to the baseline Project Estimation and Forecasting (ET): Capability to create an initial estimate of the time, effort and resources required to execute the project both from a bottom-up (detail activity / deliverable) level and a top-down (contract) level. This also includes techniques to estimate the cost and time needed to complete all the remaining work for a schedule activity and provide forecasts based on optimistic, normal and conservative scenarios Metrics (ET): Establishing metrics not only for the project (deliverables met time, scope, and cost) but establishes metrics for the outcomes the project delivers Program Benefits Tracking, Monitoring and Closure: The capability to define and implement a process to track and monitor expected benefits achievement against realization plan and close when benefits have been fully realized Change implementation planning and management (ET): Plan for and submit change requests required for project execution. Monitor status of change requests, and confirm success Project Methodology (ET): Mastery of program management methodology, tools and templates (includes program planning, schedule development, scope management and cost management) Accessibility Requirements / Standards : Understanding and application of accessibility legal requirements into design deliverables To qualify for the role you must have 8 to 10 years minimum in a corporate IT environment 10+ years of experience in project management Other relevant experience in a related technical field (application development, deployment/implementation and infrastructure) Work experience in a professional services industry, preferred Ideally, you’ll also have Knowledgeable in the Microsoft Suite of Products Practice working in a diverse and global environment Experience in Service Management tools such as ServiceNow Project management certification is preferred (PMI/CAPM or PMP, PRINCE2) Familiarity with ITIL v2 or 3 would be advantageous What we offer As part of this role, you'll work in a highly integrated, globally diverse team with the opportunity and tools to grow, develop and drive your career forward. Here, you can combine global opportunity with flexible working. The EY benefits package goes above and beyond too, focusing on your physical, emotional, financial and social well-being. Your recruiter can talk to you about the benefits available in your country. Here’s a snapshot of what we offer: Continuous learning: You’ll develop the mindset and skills to navigate whatever comes next. Success as defined by you: We’ll provide the tools and flexibility, so you can make a significant impact, your way. Transformative leadership: We’ll give you the insights, coaching and confidence to be the leader the world needs. Diverse and inclusive culture: You’ll be accepted for who you are and empowered to use your voice to help others find theirs.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1678838400,
        "job_posted_at_datetime_utc": "2023-03-15T00:00:00.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=5F_0VRsAOOcAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 96,
          "experience_mentioned": true,
          "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": false,
          "degree_mentioned": false,
          "degree_preferred": false,
          "professional_certification_mentioned": true
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null
      },
      {
        "employer_name": "Motherson Technology Services",
        "employer_logo": "https://www.motherson.com/storage/Motherson-logo.jpg",
        "employer_website": "http://www.motherson.com",
        "employer_company_type": "Manufacturing",
        "job_publisher": "LinkedIn",
        "job_id": "w3dWyQoqxmYAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "HMI Software Developer/ Specialist – Qt/QML",
        "job_apply_link": "https://in.linkedin.com/jobs/view/hmi-software-developer-specialist-%E2%80%93-qt-qml-at-motherson-technology-services-3518905075",
        "job_description": "The ideal candidate will be responsible for developing high-quality applications. They will also be responsible for designing and implementing testable and scalable code.\n\nNote: Candidates must be willing to work on-site\n\nRole: HMI Software Developer/ Specialist – Qt\n\nBrief Job Description:\n\nDevelop and maintain Qt-based HMI software using QML and C++ for Automotive Instrument Cluster or Infotainment systems.\n\nExperience/ Skill Requirements:\n\n5 to 8 years of experience with strong technical expertise in Qt-based Automotive HMI software development using QML and C++\n\nGood system level overview on technical software architecture for advanced Instrument Cluster and/or Infotainment systems\n\nExperience on automotive embedded platforms with RTOS environments based on Integrity (preferred)/ QNX/ Linux\n\nHMI Framework experience with wayland and layer manager knowledge\n\nStrong in performance optimization topics and in debugging complex HMI issues\n\nGood understanding of SDLC lifecycle and Agile delivery processes\n\nExcellent verbal and written communication skills in English\n\nFast learner who can quickly assimilate in-house HMI architectures, frameworks, tools and methods\n\nAdvanced knowledge of one or more of following topics would be desirable:\n\nDevelopment of 3D HMI applications using Qt 3D and implementation of custom shaders\n\nDevelopment of IVI middleware components based on GENIVI etc.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1678512247,
        "job_posted_at_datetime_utc": "2023-03-11T05:24:07.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=w3dWyQoqxmYAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-04-10T05:24:07.000Z",
        "job_offer_expiration_timestamp": 1681104247,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 60,
          "experience_mentioned": true,
          "experience_preferred": true
        },
        "job_required_skills": [
          "Software Development",
          "QML",
          "SQL Database",
          "Human Machine Interface",
          "SQL",
          "Programming",
          "Qt",
          "Computer Science",
          "Web Applications",
          "Databases"
        ],
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": true,
          "degree_mentioned": false,
          "degree_preferred": false,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null
      },
      {
        "employer_name": "Qt Group",
        "employer_logo": "https://upload.wikimedia.org/wikipedia/commons/a/ae/TheQtCompany_Logo.png",
        "employer_website": "http://www.qt.io",
        "employer_company_type": "Information",
        "job_publisher": "LinkedIn",
        "job_id": "Iw-0MYlalY4AAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Software Engineer, Qt Professional Services",
        "job_apply_link": "https://in.linkedin.com/jobs/view/software-engineer-qt-professional-services-at-qt-group-3531975324",
        "job_description": "About The Role\n\nImagine yourself helping industry to build next generation solutions for cars, creating futuristic dashboards for ships, analyzing satellite images, visualizing meteors with space agencies, working with multiple solutions and hardware. That’s what we do in the Qt Professional Services. We are helping world to be successful with the Qt technology.\n\nYour responsibility\n\nWe are looking for a passionate Qt Professional Services Engineer as customer lead and software developer. You will work close to our customers both visiting customer’s site and also helping out remotely from the office. The office is located in Bengaluru, India. Travelling and communicating with the customer, their managers and developers, is natural part of the job.\n\nYour main responsibility is to work in Qt Professional Services Engineer role. In this position you would help customers to solve their problems and make sure that they will succeed with their Qt projects. You would also be key technical person participating customer workshops and giving guidance on their software architecture. To make you succeed in this role you would have full support from Qt Professional Services team and whole Qt R&D.\n\nYou\n• Bachelor’s/Master's degree in Computer Science, Computer Engineering or similar\n• 5 years of experience with software development in one or more programming languages (e.g. C++, C, QML, Javascript, Python, Java, etc.)\n• Experience in Embedded software development, cross-platform software development\n• Fluency in English\n• Good communication skills\nPerhaps you\n• have experience with software development in embedded systems\n• know system architecture, software optimization, performance improvement, etc.\n\nBe yourself at Qt\n\nAt Qt, we appreciate the individual differences of our employees and aim to promote diversity through all our practices. We provide a workplace that generates equal opportunities regardless of gender, religion, national origin, age, disabilities, and any other factors. We have unique product, but our people make us exceptional. We strongly encourage people from all groups to apply – we welcome you as you are.\n\nAbout Qt\n\nQt Group (Nasdaq Helsinki: QTCOM) is a global software company, trusted by industry leaders and over 1.5 million developers worldwide to create applications and smart devices that users love. We help our customers to increase productivity through the entire product development lifecycle - from UI design and software development to quality management and deployment. Our customers are in more than 70 different industries in over 180 countries. Qt Group is headquartered in Espoo, Finland, and employs almost 700 people globally. To learn more, visit www.qt.io.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1679052744,
        "job_posted_at_datetime_utc": "2023-03-17T11:32:24.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=Iw-0MYlalY4AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-04-16T11:32:24.000Z",
        "job_offer_expiration_timestamp": 1681644744,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 60,
          "experience_mentioned": true,
          "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": true,
          "degree_mentioned": true,
          "degree_preferred": true,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": "Software engineer"
      },
      {
        "employer_name": "Commonwealth Bank",
        "employer_logo": null,
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "Jobrapido.com",
        "job_id": "DsoilZBIB8UAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Test Analyst | QT-997",
        "job_apply_link": "https://in.jobrapido.com/jobpreview/236146403",
        "job_description": "Job description\n\nResponsibilities\n\nYou will be expected to perform the following tasks and responsibilities in a manner consistent with CBA's Values and People Capabilities.\n\n- Design, build and maintain automated tests, supporting the platform framework, as part of a release engineering environment- creating the test data required to exercise various components, create scripts required to perform comprehensive integration tests, service-based and UI testing.\n- Contribute to the estimates on the test engineering efforts for various features and new initiatives as part of definition of done.\n- Execute and manage test cases and results report on test progress and defect metrics\n- Contribute to robust, scalable and high quality test automation solutions for functional, regression and performance testing.\n- Collaborate closely within your scrum team to drive testability in solution design and promote best test engineering practices in the development process\n- Establish traceability and coverage through effective mapping of test cases & scripts to acceptance criteria as defined in user story\n- Advise and apply best test engineering practice, and supporting tools and technologies to specific features and projects\n- Communicate code health and test status regularly and promptly to all project stakeholders and work with scrum / project teams to drive issue resolution\n- Using defined metrics, help continuously improve the team velocity and quality of deliverables by driving test automation optimisation\n- Up-skill team members in the domain of testing and continuous integration capabilities\n- Maximising opportunities for automation across environments (Test, UAT, Staging etc.)\n- Undertake any other tasks assigned by your manager that you have the capability to perform safely in line with relevant internal Group policies and external regulatory requirements.\n- Adhere to the . The Code of Conduct sets the standards of behaviour, actions and decisions we expect from our people.\n\nYour skills & experience\n\nEssential :\n\n- 5+ Years of experience as a Test Automation Specialist / Engineer - extensive collaboration across agile and waterfall teams\n- Experience in test automation using Selenium, C# & Specflow\n- Sound technical understanding of software development practices and life-cycles\n- Demonstrated experience in setting up and / or applying test automation frameworks for large scale Web applications using Selenium and / or LeanFT\n- The ability to analyze complex technical requirements, review architecture documents and solution design, and determine appropriate test automation approach and best engineering practices based on technical design\n- Significant experience in Analyzing functional requirements (such as User Stories), determining appropriate test approach and test conditions, documenting & executing test cases, reporting defects and tracking until closure.\n- Sound understanding and / or working knowledge of Test Driven Development (TDD) and Behavior Driven Development (BDD)\n- Experience in :\n- Source Control Management tools like GitHub\n- API / Service based testing using tools such as POSTMAN\n- Web services, REST / SOAP / XML\n\nAdditionally, exposure to the following would be highly advantageous though not essential :\n\n- Continuous Integration (CI), Continuous Delivery (CD) and DevOps\n- Cloud technologies and experience building cloud based applications\n- Containerisation technologies and tools such as Docker\n- PEGA Case Management Platform (CMP)\n- JIRA\n- Risk Mindset -All CommBank employees are expected to proactively identify and understand, openly discuss and act on current and future risks.\n\nIf you're already part of the Commonwealth Bank Group (including Bankwest), you'll need to apply through to submit a valid application.\n\nWe're keen to support you with the next step in your career.\n\nWe're aware of some accessibility issues on this site, particularly for screen reader users. We want to make finding your dream job as easy as possible, so if you require additional support please contact HR Direct on 1800 989 696.\n\nAdvertising End Date : 20 / 03 / 2023\n\n9 days ago",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1679011200,
        "job_posted_at_datetime_utc": "2023-03-17T00:00:00.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=DsoilZBIB8UAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": null,
        "job_offer_expiration_timestamp": null,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 60,
          "experience_mentioned": true,
          "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": false,
          "degree_mentioned": false,
          "degree_preferred": false,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": "Test analyst"
      },
      {
        "employer_name": "HARMAN International",
        "employer_logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Harman_International_logo.svg/250px-Harman_International_logo.svg.png",
        "employer_website": "http://www.harman.com",
        "employer_company_type": "Manufacturing",
        "job_publisher": "LinkedIn",
        "job_id": "qfhnbAaGcbUAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "QT QML",
        "job_apply_link": "https://in.linkedin.com/jobs/view/qt-qml-at-harman-international-3428193046",
        "job_description": "Job Specification: QT and QML Developer\n\nEducation & Training\n• Bachelors or Masters Degree in Computer Science or any relevant field\n\nExperience\n• Minimum 3 to 5 years of experience in software programming – Application Design and Implementation\n• Experience in UI implementation\n• Experience in infotainment display / instrument cluster projects is a plus\n• Experience in agile software development process (SCRUM)\n\nSkills\n• Experience in C++ programming for Windows based systems\n• Good hands on experience and knowledge in GUI development with Qt and QML\n• Knowledge in developing UIs (Widgets, business logic, etc.)\n• Familiar with developing Unit Tests and SW functional tests for own code\n• Practical knowledge of Visual Studio, JIRA, Confluence\n• Knowledge about CAN protocol is a plus\n• Automotive domain knowledge is a plus\n• Good communication and team player skills\n\nJob Responsibilities\n• Development of UI and business logic module with Qt and QML\n• Enable high responsiveness between UI specification/style guide development/changes and UI Simulation module delivery\n• Ensure timely delivery of simulation tasks according to product back log\n• Ensure good quality of delivery",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1678964147,
        "job_posted_at_datetime_utc": "2023-03-16T10:55:47.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=qfhnbAaGcbUAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-05-10T19:31:32.000Z",
        "job_offer_expiration_timestamp": 1683747092,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 36,
          "experience_mentioned": true,
          "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": false,
          "degree_mentioned": true,
          "degree_preferred": true,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null
      },
      {
        "employer_name": "Siemens Technology and Services Private Limited",
        "employer_logo": null,
        "employer_website": "http://www.siemens.co.in/about-us/innovations/stspl.htm",
        "employer_company_type": "Information",
        "job_publisher": "Freshersworld.com",
        "job_id": "M9iIu-0tdDIAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Lead Software Engineer C Qt/QML",
        "job_apply_link": "https://www.freshersworld.com/jobs/lead-software-engineer-c-qt-qml-jobs-in-bangalore-siemens-technology-and-services-private-limited-1702545",
        "job_description": "Siemens founded the new business unit Siemens Advanta (formerly known as Siemens IoT Services) on April 1, 2019 with its headquarter in Munich, Germany. It has been crafted to unlock the digital future of its clients by offering end-to-end support on their outstanding digitalization journey. Siemens Advanta is a strategic advisor and a trusted implementation partner in digital transformation and industrial IoT with a global network of more than 8000 employees in 10 countries and 21 offices. Highly skilled and experienced specialists offer services which range from consulting to craft & prototyping to solution & implementation and operation – everything out of one hand. Join our team to make difference! Collect and elicit stakeholder requests (explicit & implicit requests) Derive, prioritize and communicate Software Requirements Ability to understand & derive high level conceptual ideas on technical design & implementation from the user requirements. Create high quality User-story specifications Clarify all the stakeholders’ questions/clarifications on requirements and features unambiguously. Analyze and decide complaints / defects and prepare the backlog based on end customer values and priority. Drive business case development, project scoping, requirements prioritization, concept development and vertical slice planning to ensure product releases meet business objectives. Motivate development teams to achieve commitments, assist development teams in attaining maximum effective sustainable pace for development Ensure quality by evaluating results of iterations and either approve/ accept or reject results based on Doneness criteria Support effort estimations of development teams Analyze change requests and prioritize with other product backlog items Coordinate cross-feature-area development with peers to facilitate prioritized product development Deliver input for project planning & execution Internal Interactions: Product Manager, Project Lead, Quality Manager, Risk Manager, Development Team (e. g. Scrum Master, System Analyst, Architects, Developers, Testers, etc.), Usability Team, Technical Writers, etc B.E/ B. Tech/ MCA/ M. Tech 8-12 years of software development experience Desired Knowledge & Experience: Very good knowledge in software design and development using C++ & Qt/QML Very good knowledge in Design principles & patterns, OS concepts & Data structures Very good domain know-how on HMI SCADA (WinCC Classic, Professional and WinCC Unified) systems, HMI Panels and TIA portal engineering and expertise in designing workflows for PC and Panel devices. Ability to collaborate with architects, PRMs and R&D (and other stakeholders) in multiple Siemens locations to collect and prioritize product requirements. Thorough experience in Requirements Engineering, software development and feature definition activities. Good understanding of different Product Lifecycle Management processes especially Agile framework. Oversee progress of development team to ensure consistency with initial design. Develop strategies for risk mitigation, including risks associated with unstable requirements. Provide technical guidance and team members. Required Soft-skills & Other Capabilities: Drive and motivate team towards gaining business success in Industrial Automation / HMI. Strong Analytical and problem-solving Skills. Ability to decide in rapid environment and make priority calls based on situation. Ability to balance customer expectations alongside engineering team capacity. Excellent communication with global team interactions in an inter-cultural environment. Ability to work independently as well as in a team context. Need to be a strong team player with very good networking skills. Strong written and oral communication skills. Make your mark in our exciting world at Siemens. This role is based in Bangalore. You’ll also get to visit other locations in India and beyond, so you’ll need to go where this journey takes you. In return, you’ll get the chance to work with teams impacting entire cities, countries – and the shape of things to come. We’re Siemens. A collection of over 379,000 minds building the future, one day at a time in over 200 countries. We're dedicated to equality, and we encourage applications that reflect the diversity of the communities we work in. At Siemens we are always challenging ourselves to build a better future. We need the most innovative and diverse Digital Minds to develop tomorrow ‘s reality. Organization: Advanta Company: Siemens Technology and Services Private Limited Experience Level: Early Professional Job Type: Full-time",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1678254214,
        "job_posted_at_datetime_utc": "2023-03-08T05:43:34.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=M9iIu-0tdDIAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-05-08T18:29:59.000Z",
        "job_offer_expiration_timestamp": 1683570599,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 96,
          "experience_mentioned": true,
          "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": false,
          "degree_mentioned": true,
          "degree_preferred": false,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": "Software engineer"
      },
      {
        "employer_name": "Wipro",
        "employer_logo": "https://www.wipro.com/content/dam/nexus/staticsites/cloud/assets/images/header/Wipro_Logo_Secondary_Color_Digital.svg",
        "employer_website": "http://www.wipro.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "LinkedIn",
        "job_id": "JQbmQPB92yIAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "QT /QML developer",
        "job_apply_link": "https://in.linkedin.com/jobs/view/qt-qml-developer-at-wipro-3526649356",
        "job_description": "Exp -4-10 yrs.\n\nJD below\n• Strong in C, C++ and Linux. Should have hands on experience and good knowledge of working in UI.\n• Should be strong on QML, Qt, C++ with MVC\n• He/she should have worked in embedded system ( system level programming is not required ). Rather should have worked on middle ware and Application side.\n• Should have very good problem-solving ability.\n• Should have good communication skills as he/she has to interact with customer.\n• Should have worked on Agile projects.\n• Understanding and hands on experience in github, Jira\n\nwork location -Bangalore and Kochi",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1678789725,
        "job_posted_at_datetime_utc": "2023-03-14T10:28:45.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=JQbmQPB92yIAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-04-13T10:28:44.000Z",
        "job_offer_expiration_timestamp": 1681381724,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 48,
          "experience_mentioned": true,
          "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": true,
          "degree_mentioned": false,
          "degree_preferred": false,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null
      },
      {
        "employer_name": "LanceSoft India Pvt Ltd",
        "employer_logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9JaJFYCzOjczB8h4VPt5uUdWIdm3k13VrNMxo&s=0",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "Glassdoor",
        "job_id": "zxOYO4ID_I0AAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "C++ QT QML",
        "job_apply_link": "https://www.glassdoor.co.in/job-listing/c-qt-qml-lancesoft-JV_IC2940587_KO0,8_KE9,18.htm?jl=1008525111053",
        "job_description": "JD- Job Specification: Qt/QML Developer (UI Development)\n\nDescription:\n\nWe are looking for highly motivated and skilled engineers to help us design & develop UI Software Framework & Features for next-generation vehicles at our R&D Division in Bangalore, India. This role is to work closely with our counterparts in Germany to define and implement software architecture, UI Concepts & Feature development on the latest automotive embedded platforms for MBUX.\n• Minimum 8 to 12 years of experience in Architecture & software programming – UI Framework, Application Design, Implementation & testing reusable software components for embedded platforms.\n• Experience in UI implementation.\n• Development of UI modules with Qt/QML.\n• Experience in C/C++ programming with Embedded Linux knowledge.\n• Experience with version control (Git), Cmake, Unit Testing and CI/CD.\n• Enable high responsiveness between UI specification/style guide development/changes and UI module delivery.\n• Ensure timely delivery of tasks according to product back log\n• Ensure good quality of delivery\n• Experience in infotainment display / instrument cluster projects is a plus\n• Experience in agile software development process (SCRUM/KANBAN)\n• Ability to lead a team.\n• Excellent communication and team work skills.\n\nEducation/Qualifications:\n\nMaster's degree in Computer Science, software engineering or related field; or equivalent work experience.\n• Experience in C/C++ programming.\n• Good hands on experience and knowledge in GUI development with Qt/QML.\n• Ability to analyze complex problems, recognize and explain connections between cause-and-effect, and develop concrete, viable solutions, taking risks and obstacles into account.\n• Ability to manage competing project priorities and constraints.\n• Ability to analyze internal/external technology trends and developments. Active participation in collaborative opportunities to gain skills in new areas to support other team members.\n• Ability to work in inter-cultural, inter-disciplinary teams, across multiple time zones.\n• Analytical skills for continuous evaluation of ways to improve performance and behavior, focusing on efficiency and quality.\n• Knowledge in developing UIs (Views, Widgets, Business Logic, etc.)\n• Familiar with developing Unit Tests and SW functional tests for own code.\n• Demonstrated ability to implement high quality software for series development.\n• Experienced in agile collaboration models (e.g. SCRUM/KANBAN)\n• Extensive knowledge in various UI frameworks and technologies for embedded and mobile platforms such as Qt, HTML5, OpenGL & EBGuide.\n• Experience in UI development for automotive In-Vehicle Infotainment applications preferred.\n• Experience working with automotive tier-1 suppliers a plus.\n• Good communication and team player skills.\n\nJob Type: Full-time\n\nSalary: ₹1,000,000.00 - ₹2,400,000.00 per year\n\nBenefits:\n• Health insurance\n• Provident Fund\n\nSchedule:\n• Monday to Friday\n\nAbility to commute/relocate:\n• Bengaluru, Karnataka: Reliably commute or planning to relocate before starting work (Required)\n\nExperience:\n• total work: 4 years (Preferred)\n• QT QML: 2 years (Required)\n• C++: 2 years (Required)\n• UI / GUI: 1 year (Preferred)\n\nExpected Start Date: 03/04/2023",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1678665600,
        "job_posted_at_datetime_utc": "2023-03-13T00:00:00.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=zxOYO4ID_I0AAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-04-17T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1681689600,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 96,
          "experience_mentioned": true,
          "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": false,
          "degree_mentioned": true,
          "degree_preferred": true,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": 1000000,
        "job_max_salary": 2400000,
        "job_salary_currency": "INR",
        "job_salary_period": "YEAR",
        "job_highlights": {},
        "job_job_title": null
      },
      {
        "employer_name": "QuEST Global Engineering Pvt Ltd",
        "employer_logo": "https://www.quest-global.com/wp-content/uploads/2022/04/quest-global-logo-primary-500x500-1.png",
        "employer_website": null,
        "employer_company_type": null,
        "job_publisher": "TimesJobs",
        "job_id": "8zti1zF39UgAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Technical Lead Engineer- C Qt Linux",
        "job_apply_link": "https://www.timesjobs.com/job-detail/technical-lead-engineer-c-qt-linux-quest-global-engineering-pvt-ltd-bengaluru-bangalore-8-to-12-yrs-jobid-XqecYNm__SLASH__G85zpSvf__PLUS__uAgZw==",
        "job_description": "Roles & Responsibilities:Exposure to Linux Application design and development for is essential.Good understanding of the SDLC process is essentialHe/she performs software design assignments requiring initiative, resourcefulness and design experience and provides advice and guidance to other engineers or designers.Perform Requirement Management activities and manage assignments in collaboration with stakeholdersExperience writing and detailing software requirements based on use case story is essentialExperience in task estimation, work break down of given activity is mandatory.Experience working with Jira, Sprints, scrum boards is mandatorystakeholdersRequired Skills (Technical Competency):5 yrs of programming experience in C 17 or higher version, in Linux is mandatoryAble to work independently and guide a team of 1-2 engineers3 years of experience in GUI development using Qt is mandatoryShould have experience in multithreaded application design and has used UMLExperience in Cmake is mandatoryExperience in gtest is essentialExposure to Multithreading concepts and has worked with threads is essentialExperience of reverse engineering of the existing codeExperienced in writing user stories, acceptance criteria and definition of doneExposure to Java programming is desirableHas experience in developing network communication protocol like TCP/UDP or any other is essentialHas performed or experience in unit Functional /component testing to meet the design/functional needs is mandatoryExpertise i: Requirements Management - ConfluenceConfiguration Management - ClearCase, Serena Dimensions, PVCSLifecycle Management - IBM ALM / RTC, Jira, ClearQuestTesting - Component Test FrameworksMin. Qualification: B.E/B.Tech/Computer ScienceYears of Experience 8-12 Years",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1677715200,
        "job_posted_at_datetime_utc": "2023-03-02T00:00:00.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=8zti1zF39UgAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-05-01T00:00:00.000Z",
        "job_offer_expiration_timestamp": 1682899200,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 60,
          "experience_mentioned": true,
          "experience_preferred": false
        },
        "job_required_skills": [
          "udp",
          "c",
          "software design",
          "software requirements",
          "uml",
          "linux",
          "multithreading",
          "gui development",
          "clearcase",
          "java programming"
        ],
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": false,
          "degree_mentioned": true,
          "degree_preferred": false,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": "Lead engineer"
      },
      {
        "employer_name": "Leica Microsystems",
        "employer_logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Leica_Microsystems.svg/1200px-Leica_Microsystems.svg.png",
        "employer_website": "http://www.leica-microsystems.com",
        "employer_company_type": "Computer Services",
        "job_publisher": "LinkedIn",
        "job_id": "PZIw38SAAdIAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "Senior Software Engineer I (C++, QT/QML)",
        "job_apply_link": "https://in.linkedin.com/jobs/view/senior-software-engineer-i-c%2B%2B-qt-qml-at-leica-microsystems-3530575886",
        "job_description": "Leica Microsystems –Sr Software Engineer ( QT\\QML with C++)\n\nLeica Microsystems has helped shape the future of microscopy for over 170 years by developing groundbreaking optical and digital solutions. As a global leader, we’re driven by continuous improvement to excite our customers and to create the best work environment for our people. Customer focus, innovation, and teamwork are at the core of our culture and the foundation of our success.\n\nWant to be part of a company whose products are part of cutting-edge research around the world? Join Leica Microsystems in our commitment for brilliant solutions and insight.\n\nLeica Microsystems is proud to work alongside a community of nine fellow Danaher Life Sciences companies. Together, we’re pioneering the future of science and medicine, developing products that enable researchers in the fight to save lives.\n\nSr Software Engineer\n\nCome join a fantastic team! Your role will be located in IDC Bangalore.\n\nYour Responsibilities\n• Design, implement, verify and document software system.\n• In collaboration with the project team, design and verify architecture of sub-systems, components and modules.\n• Develop software requirements, document software requirement specifications and software architecture design.\n• Contribute to continuous improvement of development processes and CI/CD infrastructure.\n• Proactively collaborate with project stakeholders, including application developers and product managers, to identify efficient technical solutions.\n• Develop design documents w.r.t functional and software specification.\n• Mentor junior and mid-level developers, perform code and design reviews.\n\nYOUR PROFILE\n• 5 years of experience on QT development & C++\n• Proficiency in coding with best practices while developing code in QT and C++\n• Proficiency in programming user interfaces and data visualization with the QT Framework (QML and Qt/C++)\n• Must have development experience in windows & Linux based environment\n• Must have experience on object-oriented analysis and design (OOA and OOD)\n• Must have good knowledge of design patterns\n• Must have good knowledge of software life cycle and architecture\n• Must have good knowledge on data structure and algorithms.\n• Must have excellent analytical and problem-solving skills\n• Must be aware of Agile methodology\n• Qualification required: B.E/B.Tech/MCA.\n• Strong analytical thinking .\n• Good communication skills and strategic thinking\n\nWhat We Offer (examples to pick from)\n\nThis information will be used on your job profile. (Multiple selection possible, max. 6 points)\n\nCompensation:\n• Attractive salary and pension package\n• Employees have the option to work from home up to 2 days/week\n• We offer flexible working time models\n• Equal pay is a matter of course for us\n\nTraining & development:\n• Learn all about Kaizen, PSP's and Muda as part of our Danaher Business System (DBS) trainings - if you believe in continuous improvement like us\n• We offer employees a wide range of training opportunities (including virtual) in languages, technology and the Danaher Business System (DBS) Academy\n• We support employees in their professional and personal development\n• We support and develop employees in leadership positions\n• Our employees have international development opportunities\n• Do you have ambitious goals? Then we could be a perfect match. Performance is rewarded with us - we challenge and support you in your career planning\n\nD+I and work-life balance:\n• Design your place of work so that professional and private demands are no longer mutually exclusive\n• Child(ren) and career are not mutually exclusive - we offer family-friendly job models\n• We assume social responsibility (Corporate Social Responsibility)\n• We have no room for prejudices and stereotypes. We promote equal opportunities, diversity and inclusion. #Charterof Diversity\n\nTeam:\n• We enable independent work within a committed, international team\n• We offer our employees modern virtual work in an exciting international environment - with both German and American guiding cultures\n• Here you will find a friendly team that can work hard and party just as hard\n• Here you will find a reliable team that is a pleasure to work with\n• We offer a balance between support and autonomy to achieve your own goals in an international environment\n• With us you get the chance to successfully contribute your own ideas\n• We offer a solid onboarding program including a one-month orientation phase\n• A pleasant working atmosphere is important to us. This also includes celebrating successes\n• We are particularly interested in long-term cooperation\n• Do you want creative freedom and responsibility? We work in flat hierarchies\n• We want to move and change things, we clearly need doers\n\nDIVERSITY AT LEICA\n\nWe are an equal opportunity employer. We evaluate qualified applicants without regard to race, color, national origin, religion, gender, age, marital status, disability, veteran status, sexual orientation, gender identity, or any other characteristic protected by law.\n\nGET MORE INSIGHT\n\nLearn more about what we do and who we are by watching our company video “We Are Leica”: https://www.youtube.com/watch?v=1zHmalqMXN4\n\nAre you interested to discover new opportunities in an innovative, team-oriented environment?\n\nDo apply online - we are looking forward to your application!\n\nWhen you join us, you’ll also be joining Danaher’s global organization, where 80,000 people wake up every day determined to help our customers win. As an associate, you’ll try new things, work hard, and advance your skills with guidance from dedicated leaders, all with the support of powerful Danaher Business System tools and the stability of a tested organization.\n\nAt Danaher, we value diversity and the existence of similarities and differences, both visible and not, found in our workforce, workplace and throughout the markets we serve. Our associates, customers and shareholders contribute unique and different perspectives as a result of these diverse attributes.\n\nIf you’ve ever wondered what’s within you, there’s no better time to find out.",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1678968294,
        "job_posted_at_datetime_utc": "2023-03-16T12:04:54.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=0&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=PZIw38SAAdIAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-04-15T12:04:54.000Z",
        "job_offer_expiration_timestamp": 1681560294,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 60,
          "experience_mentioned": true,
          "experience_preferred": false
        },
        "job_required_skills": null,
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": true,
          "degree_mentioned": true,
          "degree_preferred": false,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": "Software engineer"
      },
      {
        "employer_name": "Mercede",
        "employer_logo": null,
        "employer_website": "http://www.mercedes-benz.com",
        "employer_company_type": "Manufacturing",
        "job_publisher": "LinkedIn",
        "job_id": "BOZMQejwKkMAAAAAAAAAAA==",
        "job_employment_type": "FULLTIME",
        "job_title": "SP_C++/QT Frontend Developer",
        "job_apply_link": "https://in.linkedin.com/jobs/view/sp-c%2B%2B-qt-frontend-developer-at-mercede-3517405788",
        "job_description": "UI development using languages C++17, QML/JS, IDL, YAML\n\nJenkins, GIT, Artifactory (CI/CD pipeline) knowledge.\n\nExperience with frameworks Qt 5, Qt Quick, FaceLift, Google Test.\n\nKnowledge of REST/JSON , API development.\n\nExperience with build tools CMake, GCC\n\nMust provide customers with ongoing technical support.\n\nEstablishing a good working relationship with the business\n\nScrum and agile experience.\n\nQualification\n\nEducation: Bachelor s Degree in Information technology or Engineering.\n\nYears of Experience: 3-5 years\n\n5+ years of C++17, QML/JS, IDL, YAML languages ,REST/JSON API development.\n\nExperience developing cross-platform desktop applications\n\nExperience with GUI implementation using frameworks - Qt 5, Qt Quick, FaceLift, Google Test.\n\nExperience in real-time with build tools CMake, GCC.\n\nExperience in scrum and agile methodologies.\n\nGood current knowledge of Unix/Linux environments\n\nExperienced with CI/CD tools, Docker, kubernetes and AWS will be highly appreciated.\n\nExperienced in professional software development best practices including adherence to coding standards, peer code reviews, build processes, and unit testing\n\nExperience with developing, enhancing and integrating cross-platform SDKs is a plus\n\nExperience developing C libraries used by multiple other languages is a plus\n\nExperience with Restful Web Services (JAX-RS), JAXB, XSLT knowledge\n\nCapable of delivering secure, high quality code and documentation.\n\nSkill Management Requirements\n\nHas to be a good team player as well as individual contributor who supports and provides when required\n\nAble to understand client needs. Takes responsibility of the tasks assigned and can find solutions with minimum assistance\n\nOutside the box thinking and adaptability\n\nGood understanding of the existing technical solutions and their implementation\n\nAwareness of the influence new technologies have on existing technical solutions\n\nHas a basic knowledge of system integration from practical and/or theoretical experience\n\nHas good understanding of technical solutions and its influences on customer s business\n\n, *\n\nBachelor s Degree in Information technology or Engineering\n\nThis job is provided by Shine.com",
        "job_is_remote": false,
        "job_posted_at_timestamp": 1676288592,
        "job_posted_at_datetime_utc": "2023-02-13T11:43:12.000Z",
        "job_city": "Bengaluru",
        "job_state": "KA",
        "job_country": "IN",
        "job_latitude": 12.971599,
        "job_longitude": 77.59457,
        "job_benefits": null,
        "job_google_link": "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=qt+manager,+banglore,+india&start=10&chips=requirements:years3plus&schips=requirements;years3plus&lrad=20&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=qt+manager,+banglore,+india&htidocid=BOZMQejwKkMAAAAAAAAAAA%3D%3D",
        "job_offer_expiration_datetime_utc": "2023-04-09T11:43:12.000Z",
        "job_offer_expiration_timestamp": 1681040592,
        "job_required_experience": {
          "no_experience_required": false,
          "required_experience_in_months": 60,
          "experience_mentioned": true,
          "experience_preferred": true
        },
        "job_required_skills": null,
        "job_required_education": {
          "postgraduate_degree": false,
          "professional_certification": false,
          "high_school": false,
          "associates_degree": false,
          "bachelors_degree": true,
          "degree_mentioned": true,
          "degree_preferred": true,
          "professional_certification_mentioned": false
        },
        "job_experience_in_place_of_education": false,
        "job_min_salary": null,
        "job_max_salary": null,
        "job_salary_currency": null,
        "job_salary_period": null,
        "job_highlights": {},
        "job_job_title": null
      }
    ]
  }

  trackByFn(index: number, job: Job): string | null {
    return job.job_id;
  }

}